### PR TITLE
Feature/update manifest

### PR DESCRIPTION
**Pull request by kfang4**
~~- Remove multiome docker image (used in R version of workflow)~~
- Remove path from output files in manifest files
- Currently, we write manifest workflows with the subworkflow and subworkflow_version, but instead, write them with the whole workflow. This means that another variable needs to be updated when workflow is updated (preprocess version, cohort analysis version, workflow version). Example:
```
filename    timestamp      workflow              workflow_version      workflow_release
f.tsv       2024-06-04..   harmonized_pmdbs      v2.1.0                https://github.com/ASAP-CRN/harmonized-wf-dev/releases/tag/harmonized_pmdbs_analysis-v2.1.0
```

### CODE REVIEW

**Comment by kfang4** [comment]
To do:
- Add file checksums into the manifest (and the metadata files, generated upon file upload)

**Comment by kfang4** [comment]
To note for `promote_staging_data` script:
- Changes in `feature/update-manifest` include renaming workflow to _just_ harmonzied_pmdbs rather than preprocess and cohort_analysis in manifest files
- Changes in `feature/update-manifest` include adding hash (md5) in manifest files
- Changes in `feature/update-manifest` include adding the GitHub release link in manifest files

**Comment by ergonyc** [comment]
The changes look like to be mostly in the wdl weeds.  Look sensible and overall clarifying to me.

**Comment by kfang4** [comment]
Renamed workflow from `harmonzied_pmdbs` to `pmdbs_sc_rnaseq_analysis`

**Pull request merged**
